#pragma once

// Generated by cp77ida.py on 2023-04-20 for Cyberpunk 2077 v.1.62
// DO NOT MODIFY. USE tools\ida\scan.py TO GENERATE THIS FILE.

#include <cstdint>

namespace Red::Addresses
{
constexpr uintptr_t ImageBase = 0x140000000;

constexpr uintptr_t Main = 0x1401A0330 - ImageBase; // 40 53 48 81 EC ? ? ? ? FF 15 ? ? ? ? E8 ? ? ? ? E8 ? ? ? ?, expected: 1, index: 0
constexpr uintptr_t InvokeSCC = 0x140A97FC0 - ImageBase; // 48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 4C 89 74 24 20 55 48 8D AC 24 30 B0 FF FF B8 D0 50 00 00, expected: 1, index: 0
constexpr uintptr_t LogChannel = 0x1401F7C60 - ImageBase; // 4C 8B DC 49 89 5B 08 49 89 73 18 57 48 83 EC 70 48 8B 02 ? ? ? ? ? ? ? FE 42 62 4D 8D 43 10 33 FF 45 33 C9 49 89 7B 10 48 8B DA 48 89 7A, expected: 1, index: 0

constexpr uintptr_t CBaseEngine_LoadScripts = 0x140A83F00 - ImageBase; // 48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 20 49 8B F9 41 C6 81 A0 02 00 00 01, expected: 1, index: 0
constexpr uintptr_t CBaseEngine_MainLoopTick = 0x140A84610 - ImageBase; // 40 56 41 56 48 83 EC 78 48 8B F1 0F 29 7C 24 50 48 8D 4C 24 38 0F 28 F9 E8 ? ? ? ? 48 8D 8C 24 A0 00 00 00, expected: 1, index: 0

constexpr uintptr_t ISerializable_SetReference = 0x1401BA100 - ImageBase; // 40 53 48 83 EC 30 48 8B 02 48 8B D9 48 89 44 24 20 48 8D 4C 24 20 48 8B 42 08 48 89 44 24 28 E8, expected: 24, index: 1

constexpr uintptr_t JobHandle_Wait = 0x142C4A050 - ImageBase; // 40 53 48 83 EC 30 48 8B D9 33 D2 48 8B 0D ? ? ? ? E8, expected: 1, index: 0

constexpr uintptr_t ResourceBank_ForgetResource = 0x140266FC0 - ImageBase; // 48 89 5C 24 10 48 89 6C 24 20 56 57 41 54 41 56 41 57 48 83 EC 30 4C 8B F1 49 8B F8, expected: 1, index: 0

constexpr uintptr_t ResourceDepot_LoadArchives = 0x1430499C0 - ImageBase; // 48 8B C4 4C 89 48 20 55 53 56 41 55 48 8D 68 B1 48 81 EC C8 00 00 00 49 8B 18 4C 8B EA, expected: 1, index: 0
constexpr uintptr_t ResourceDepot_DestructArchives = 0x1430490E0 - ImageBase; // 85 D2 0F 84 ? ? ? ? 48 89 74 24 10 57 48 83 EC 20 8D 42 FF 48 89 5C 24 30 48 8D 34 80 8B FA, expected: 1, index: 0
constexpr uintptr_t ResourceDepot_RequestResource = 0x143048E20 - ImageBase; // 48 89 5C 24 18 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 D9 48 81 EC B0 00 00 00 33 F6 4C 8B FA, expected: 1, index: 0

constexpr uintptr_t ScriptBinder_ctor = 0x140282AC0 - ImageBase; // 48 89 5C 24 08 57 48 83 EC 20 48 89 11 48 8B D9 48 C7 41 40 00 00 00 00 49 8B 48 38 48 85 C9, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_Bind = 0x140282C00 - ImageBase; // 48 89 5C 24 08 48 89 74 24 10 48 89 7C 24 18 44 88 4C 24 20 55 41 54 41 55 41 56 41 57 48 8B EC, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_ResolveNatives = 0x1402859C0 - ImageBase; // 48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 48 83 EC 20 48 8B 32, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_ResolveTypes = 0x140285BD0 - ImageBase; // 40 53 57 41 57 48 81 EC 80 00 00 00 48 8B 1A 4C 8B F9 8B 42 0C 48 8D 3C C3 48 3B DF 0F 84, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_CreateClass = 0x1402831D0 - ImageBase; // 48 89 5C 24 18 48 89 74 24 20 57 41 56 41 57 48 83 EC 50 0F B6 82 89 00 00 00 4C 8B F2 33 DB, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_CreateProperties = 0x140283440 - ImageBase; // 4C 89 44 24 18 48 89 54 24 10 55 53 41 54 41 55 41 56 41 57 48 8D AC 24 18 FF FF FF, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_CreateEnum = 0x140284250 - ImageBase; // 4C 89 44 24 18 48 89 4C 24 08 55 53 56 41 57 48 8B EC 48 83 EC 68 48 83 7A 18 00 48 8D 4D 30, expected: 2, index: 1
constexpr uintptr_t ScriptBinder_CreateBitfield = 0x140282FA0 - ImageBase; // 4C 89 44 24 18 48 89 4C 24 08 55 53 56 41 57 48 8B EC 48 83 EC 68 48 83 7A 18 00 48 8D 4D 30, expected: 2, index: 0
constexpr uintptr_t ScriptBinder_CreateFunction = 0x140284480 - ImageBase; // 4C 89 44 24 18 48 89 4C 24 08 55 53 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 E1 48 81 EC 98 00 00 00 44 0F B6 9A 98 00 00 00, expected: 1, index: 0
constexpr uintptr_t ScriptBinder_TranslateBytecode = 0x140284F80 - ImageBase; // 4C 8B DC 55 53 57 41 55 49 8D 6B A1 48 81 EC 98 00 00 00 48 8B 1A 4C 8B E9 8B 42 0C 48 8D 3C C3, expected: 1, index: 0

constexpr uintptr_t ScriptBundle_ctor = 0x14027DF60 - ImageBase; // 48 89 5C 24 10 48 89 74 24 18 57 48 83 EC 20 48 8B F9 48 8D 4C 24 30 E8 ? ? ? ? 33 F6, expected: 8, index: 0
constexpr uintptr_t ScriptBundle_dtor = 0x14027E1B0 - ImageBase; // 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B D9 E8 ? ? ? ? 48 8D 8B 38 01 00 00, expected: 1, index: 0
constexpr uintptr_t ScriptBundle_Read = 0x1402802A0 - ImageBase; // 40 53 48 83 EC 30 48 8B D9 4C 8B C2 48 8B 0D ? ? ? ? 48 8D 54 24 50 41 B9 01 00 00 00 48 8B 01, expected: 1, index: 0

constexpr uintptr_t ScriptValidator_Validate = 0x140281390 - ImageBase; // 48 8B C4 4C 89 40 18 48 89 48 08 55 53 48 8D 68 A1 48 81 EC A8 00 00 00 48 89 70 10 48 8B DA, expected: 1, index: 0
}
