#pragma once

#include <algorithm>
#include <concepts>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <map>
#include <memory>
#include <set>
#include <source_location>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

#include <RED4ext/RED4ext.hpp>

#include <RED4ext/ResourceDepot.hpp>
#include <RED4ext/ResourceLoader.hpp>
#include <RED4ext/Scripting/Natives/Generated/Box.hpp>
#include <RED4ext/Scripting/Natives/Generated/CMesh.hpp>
#include <RED4ext/Scripting/Natives/Generated/DynamicTexture.hpp>
#include <RED4ext/Scripting/Natives/Generated/EInputKey.hpp>
#include <RED4ext/Scripting/Natives/Generated/IDynamicTextureGenerator.hpp>
#include <RED4ext/Scripting/Natives/Generated/Transform.hpp>
#include <RED4ext/Scripting/Natives/Generated/community/CommunityTemplateData.hpp>
#include <RED4ext/Scripting/Natives/Generated/community/SpawnEntry.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/ColliderComponent.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/ComponentsStorage.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/Entity.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/EntityID.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/IComponent.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/ITransformBinding.hpp>
#include <RED4ext/Scripting/Natives/Generated/ent/RenderHighlightEvent.hpp>
#include <RED4ext/Scripting/Natives/Generated/game/EntityStubComponentPS.hpp>
#include <RED4ext/Scripting/Natives/Generated/game/ICameraSystem.hpp>
#include <RED4ext/Scripting/Natives/Generated/game/ICommunitySystem.hpp>
#include <RED4ext/Scripting/Natives/Generated/game/IEntityStubSystem.hpp>
#include <RED4ext/Scripting/Natives/Generated/game/IGameSystem.hpp>
#include <RED4ext/Scripting/Natives/Generated/game/ScriptableSystem.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/CacheWidget.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/CharacterEvent.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/ControllerProcessor.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/DrawArea.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/EAnchor.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/HUDLayer.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/HUDLayerDefinition.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/HudEntriesResource.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/HudWidgetSpawnEntry.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/IEffect.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/ISystemRequestsHandler.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/IWidgetComponentWrapper.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/IWidgetController.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/ImageWidget.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/Layer.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/MenuLayer.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/MultiChildren.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/PropertyManager.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/Rectangle.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/SpawningProcessor.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/StyleResourceWrapper.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/UserData.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/VirtualWindow.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/WatermarksLayer.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/Widget.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/WidgetLibraryItemInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/WidgetLibraryResource.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/WidgetLogicController.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/WorldLayer.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/anim/Definition.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/anim/Event.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/anim/Interpolator.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/anim/Processor.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/anim/Sequence.hpp>
#include <RED4ext/Scripting/Natives/Generated/ink/anim/SequenceTargetInfo.hpp>
#include <RED4ext/Scripting/Natives/Generated/physics/TraceResult.hpp>
#include <RED4ext/Scripting/Natives/Generated/rend/PostFx_ScanningState.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/AreaShapeNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/BendedMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/BendedMeshNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/CommunityRegistryNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/CompiledCommunityAreaNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/EntityNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/EntityNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/EntityProxyMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/FoliageNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/GenericProxyMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/GeometryShapeNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/GlobalNodeID.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/INodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/IRuntimeSystem.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/InstancedDestructibleMeshNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/InstancedMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/InstancedMeshNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/MeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/MeshNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/Node.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/NodeInstanceRegistry.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/PhysicalDestructionNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/PrefabProxyMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/RoadProxyMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/RuntimeSystemNodeStreaming.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/StaticDecalNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/StaticDecalNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/StaticLightNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/StaticOccluderMeshNode.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/StreamingSector.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/TerrainMeshNodeInstance.hpp>
#include <RED4ext/Scripting/Natives/Generated/world/TerrainProxyMeshNode.hpp>
#include <RED4ext/Scripting/Natives/ScriptGameInstance.hpp>

#include <nameof.hpp>
#include <semver.hpp>

#include <FileWatch.hpp>

#include "Core/Raw.hpp"
#include "Core/Stl.hpp"

#include "Red/Alias.hpp"
#include "Red/Engine.hpp"
#include "Red/Specializations.hpp"
#include "Red/TypeInfo.hpp"
#include "Red/Utils.hpp"

#include "Red/Addresses/Library.hpp"
